//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject_Arif.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountHolder
    {
        public int AccountId { get; set; }
        public string Name { get; set; }
        public string PhoneNo { get; set; }
        public string Address { get; set; }
        public string ImagePath { get; set; }
        public int BranchID { get; set; }
    
        public virtual Branch Branch { get; set; }
    }
}
