//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject_Arif.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class BAccountHolder
    {
        public int BAccountHolderID { get; set; }

        [Required(ErrorMessage = "This Field is required")]
        [StringLength(30, MinimumLength = 2, ErrorMessage = "Enter minimum 2 or maximum 30 character")]
        public string Name { get; set; }

        [Required(ErrorMessage = "This Field is required")]
        public string Occupation { get; set; }

        [Required(ErrorMessage = "This Field is required")]
        public string ContactNo { get; set; }
        [Required(ErrorMessage = "This Field is required")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required(ErrorMessage = "This Field is required")]
        [Display(Name ="Upload Image")]
        public string ImagePath { get; set; }


        public HttpPostedFileBase ImageUpload { get; set; }

        public BAccountHolder()
        {
            ImagePath = "~/AppFiles/Images/default.png";
        }
    }
}
