//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject_Arif.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="This Field Is Required")]
        public string Name { get; set; }
        public int Age { get; set; }

        [Required(ErrorMessage = "This Field Is Required")]
        public string State { get; set; }
        [Required(ErrorMessage = "This Field Is Required")]
        public string Country { get; set; }
    }
}
