//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject_Arif.Models
{
    using MVCProject_Arif.CustomValidation;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Loan
    {
        public int LoanId { get; set; }

        [Required(ErrorMessage = "This Field is required")]
        [Display(Name = "Customer Name")]
        public string CustomerName { get; set; }
        public Nullable<int> BranchID { get; set; }
        [DataType(DataType.Date)]
        [CustomHireDate(ErrorMessage = "Hire Date must be less than or equal to Today's Date")]
        [Display(Name = "Issue Date")]
        public System.DateTime IssueDate { get; set; }
        [Required(ErrorMessage = "This Field is required")]
        [Display(Name = "Principle Amount")]
        public int PrincipleAmount { get; set; }

        [Required(ErrorMessage = "This Field is required")]
        public int Interest { get; set; }
        public Nullable<int> Total { get; set; }

        public virtual Branch Branch { get; set; }
    }
}
